baseURL = "https://nizmow.github.io/"
languageCode = "en-nz"
title = "Neil's Notes"
theme = "hugo-flex"
staticDir = "static"

[params]
    width = "42rem"
    color = "#465E75"
    AuthorName = "Neil Houghton"

[permaLinks]
    posts = "/:year/:month/:title/"

[menu]
    [[menu.nav]]
    name = "Posts"
    url = "posts/"
    weight = 1.0

    [[menu.nav]]
    name = "Categories"
    url = "categories/"
    weight = 2.0
    