baseURL: 'https://blog.nizmow.net/'
languageCode: en-nz
title: Neil's Notes
theme: hugo-flex
staticDir: static
pygmentsUseClasses: true
pygmentsCodeFences: true

params:
  width: 42rem
  color: '#465E75'
  AuthorName: Neil Houghton
  summaries: true
  css:
    - stylesheets/syntax.css
    - stylesheets/custom.css
  footer: |
    <script>
      (function() {
        window.counter = 'https://blog_nizmow_net.goatcounter.com/count'

        var script = document.createElement('script');
        script.async = 1;
        script.src = '//gc.zgo.at/count.js';
        var ins = document.getElementsByTagName('script')[0];
        ins.parentNode.insertBefore(script, ins)
      })();
    </script>

permaLinks:
  posts: '/:year/:month/:title/'

menu:
  nav:
    - name: About
      url: about/
      weight: 1
    - name: Posts
      url: posts/
      weight: 2
    - name: Tags
      url: tags/
      weight: 3
