name: Publish
on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Hugo
        uses: crazy-max/ghaction-hugo@v1
        with:
          version: latest
          args: --cleanDestinationDir --minify --verbose
      - name: Deploy
        if: success() && github.event_name != 'pull_request'
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: public
          fqdn: blog.nizmow.net
        env:
            GITHUB_PAT: ${{ secrets.BLOG_PUBLISH_PAT }}
